version: "3.8"

services:
  database:
    image: bmassengale/todo-postgres:1.0
    ports:
      - target: 5432
        published: 5432
    networks:
      - todo-network
    container_name: postgres
    user: postgres

    
  api:
    image: bmassengale/todo-api:1.0
    ports:
      - target: 80
        published: 8080
    networks:
      - todo-network
    container_name: aspnet-api


  client:
    tty: true
    image: bmassengale/todo-client:1.0
    ports:
      - target: 3000
        published: 3000
    networks:
      - todo-network
    container_name: react-frontend


networks:
  todo-network:
    external: true